language: java
jdk:
  - openjdk8
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.gradle'
before_install:
  - chmod +x ./gradlew
script: "./gradlew clean build"

notification:
  email:
    recipients:
      - "unknown9732@naver.com"
