language: java
jdk:
  - openjdk8
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.gradle'
before_install:
  - chmod +x ./gradlew
script: "./gradlew clean build"

notification:
  email:
    recipients:
      - "unknown9732@naver.com"


before_deploy:
  - zip -r wing-api *
  - mkdir -p deploy
  - mv wing-api.zip deploy/wing-api.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wing-api-build
    regin: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: wing-api-build
    key: wing-api.zip

    bundle_type: zip
    application: wing-api
    deployment_group: wing-api-group
    region: ap-northeast-2
    wait-until-deployed: true